### ISSUE TITLE
Keyboard shortcut generated from UI does not handle case correctly

### ISSUE THREAD

**Issue by oknozor** [lapce/lapce#1312]
## Lapce Version

`0.2.0`

## System information

Linux
archlinux 5.19.9-arch1-1
x86_64 GNU/Linux

## Describe the bug

Generating a key-mappings from the UI produce the following entry in `keymap.toml` : 

```toml
[[keymaps]]
command = "move_line_up"
mode = "i"
key = "Ctrl+Shift+U"
```
This does not trigger "move_line_up". 

Do get it working I need to manually edit `keymap.toml`: 
key = "Ctrl+Shift+u"

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used
