### ISSUE TITLE
Select from suggestions list

### ISSUE THREAD

**Issue by radu-matei** [lapce/lapce#133]
While writing code, the list of possible suggestions pops up:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/13103165/158814731-964a24d3-9302-4d95-a23b-01876608857d.png">

It would be very helpful to select using the arrow keys (or mouse cursor) and autocomplete the selected item.

**Comment by follower** [comment]
As another data point:

 * I changed the `Keybinding` for `list.select` (with `When` of `list_focus`) from `Enter` to `Shift + Enter` and then `Shift + Enter` _did_ use the selected code completion _but..._
 * ...then when using the command palette (via `Ctrl + Shift + p`) the matching command was no longer executed via just `Enter`--it _also_ required `Shift + Enter` to execute the selected/highlighted command.
   
   Perhaps this indicates a possible bug location.

**Comment by follower** [comment]
Okay, so, this is an interesting discovery...

When I changed the `Keybinding` to `Shift + Enter` the content of the config file `~/.config/lapce/keymaps.toml` became:

```toml
[[keymaps]]
command = "list.select"
when = "list_focus"
key = "Shift+Enter"

[[keymaps]]
command = "-list.select"
when = "list_focus"
key = "Enter"
```

_...but_ if I then manually changed the `command = "-list.select"` line to `command = "list.select"` (possibly along with an application restart) then suddenly _both_ `Enter` & `Shift + Enter` worked as expected for _both_ the code completion _and_ the command palette.

i.e. the content of `~/.config/lapce/keymaps.toml` is now:

```toml
[[keymaps]]
command = "list.select"
when = "list_focus"
key = "Shift+Enter"

[[keymaps]]
command = "list.select"
when = "list_focus"
key = "Enter"
```

(And there are multiple entries for `list.select` with `Enter` in the keybinding GUI.)

This suggests to me that the underlying issue may indeed be related to prioritization/order of input processing.

**Comment by follower** [comment]
In case it's useful for anyone else in the interim, this is what I've ended up with for the content of `~/.config/lapce/keymaps.toml` so that code completion (&"Undo"/"Redo" mostly) works more like I expected (via arrow keys & enter/return key):

```toml
[[keymaps]]
command = "list.select"
when = "list_focus"
key = "Enter"

[[keymaps]]
command = "list.next"
when = "list_focus"
key = "ArrowDown"

[[keymaps]]
command = "list.previous"
when = "list_focus"
key = "ArrowUp"

[[keymaps]]
command = "redo"
key = "Ctrl+Z"
```

(Note that `Ctrl+Shift+z` appears to be represented as `Ctrl+Z` in the `.toml` file & then gets converted to `Ctrl+Shift+Z` in the GUI.)
