### ISSUE TITLE
[Keybindings] Command disappear switching from default value to empty 

### ISSUE THREAD

**Issue by banditopazzo** [lapce/lapce#1632]
## Lapce Version

v0.2.1

## System information

Arch Linux

## Describe the bug

Removing the default keybind for a `Command` makes the `Command` disappear from the `Keybindings` list 

## Additional information

I wanted to remove the default keybind for a `Command`, so I clicked on the keybind combination, the window to re-assign it appeared and I clicked on `Save` leaving the field empty. After that the `Command` disappeared from the list.

Looking in the `keymaps.toml` file the following entry appeared:

```toml
[[keymaps]]
command = "-insert_cursor_end_of_line"
mode = "i"
key = "Alt+Shift+i"
``` 

If I delete this entry from `keymaps.toml` the commands appeared again in the `Command` list with its default value, in this case `Alt+Shift+i`.
