### ISSUE TITLE
Plugin: C/C++ (clangd) No such file or directory (os error 44)

### ISSUE THREAD

**Issue by MK-Alias** [lapce/lapce#1792]
## Lapce Version
0.2.4

## System information
Arch Linux x64: Kernel: 6.0.10-arch2-1

## Describe the bug
When I install C/C++ plugin and start a lapce session in a folder with C/C++ code - which has a compile_flags.txt that works just fine on other editors (Sublime, Emacs, VScode) - I get prompted with the message: "Plugin: C/C++ (clangd) No such file or directory (os error 44)". from there on only syntax highlighting works., no LSP features.

## Additional information

Currently - for whatever reason - Arch has LLVM 14.0 in its repositories. So I have a clangd-14.0.6 in my path. Perhaps this is part of the problem!?

This editor looks pretty sweet. I'm already excited for the v1.0 production release.! That's probably going to take a while, but i can wait to see it.

**Comment by Ephemereh** [comment]
I  think you should set path to clangd in the settings.

**Comment by MK-Alias** [comment]
Hi, thanks for the response! Adding the absolute path to clangd did solve the problem! I've could have sworn that i already tried this, but probably made a mistake somehow.

adding this to the `settings.toml` fixes it on my ArchLinux installation (be-sure to install clangd `sudo pacman -S clangd`)

```toml
[lapce-cpp-clangd]
"volt.serverPath" = "/usr/bin/clangd"
```

Also for those reading into this, you might want to concider also adding `--header-insertion=never` to the serverArgs. This will get rid of auto-inclusion of headers. Some people might enjoy it, others - like me - dont.

```toml
[lapce-cpp-clangd]
"volt.serverPath" = "/usr/bin/clangd"
"volt.serverArgs" = [
    "--header-insertion=never"
]
```
