### ISSUE TITLE
Cannot map key  `Ctrl`+`[` to "Modal close" action

### ISSUE THREAD

**Issue by tmfink** [lapce/lapce#2021]
## Lapce Version

Reproduced in master at aa66b3f6d50080be32a8489e25d7edea56af4e53.

## System information

Pop!_OS 22.04 LTS

## Describe the bug
Trying to set  `Ctrl`+`[`  as a shortcut for "Close Modal" in the GUI does not work.
Instead, the "outdent line" action is performed.
The default key `Escape` still works for closing modal.

**Note**: in normal terminals, `Ctrl`+`[` (i.e. `^[`) is treated the same as the `Escape` key, which I normally use in Vim.
https://www.systutorials.com/docs/linux/man/4-console_codes/

## Additional information

The GUI generates `keymaps.toml`:
```toml
[[keymaps]]
command = "modal.close"
when = "modal_focus"
key = "Ctrl+["

[[keymaps]]
command = "-modal.close"
when = "modal_focus"
key = "Escape"
```

Possible issues:
* Having more than one key map to the same action
* Adding a shortcut that conflicts with built-in shortcuts
