### ISSUE TITLE
Automate Winget releases

### ISSUE THREAD

**Issue by Araxeus** [lapce/lapce#2227]
There's this awesome semi-official action – https://github.com/vedantmgoyal2009/winget-releaser

Used by many, including for example [nushell ](https://github.com/nushell/nushell/blob/main/.github/workflows/winget-submission.yml), [pnpm](https://github.com/pnpm/pnpm/blob/cdd5eb6b5a23b06b68ac40f925155f4d07623d53/.github/workflows/update-latest.yml#L30-L40), [vscodium](https://github.com/VSCodium/vscodium/blob/141716f439e31660e63634754cd8d7caeaedb197/.github/workflows/stable-windows.yml#L123-L131), [neovim](https://github.com/neovim/neovim/blob/c1514d7e6762ed62dee027ecc29bafd4aae2206e/.github/workflows/release.yml#L220-L246), [jacket](https://github.com/Jackett/Jackett/blob/master/.github/workflows/winget.yml), and [many more](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+WinGet+Releaser)

It is easy to set up and will automatically update https://github.com/microsoft/winget-pkgs/tree/master/manifests/l/Lapce/Lapce

Here's an example action.yml you could use:

```yml
name: Submit to Windows Package Manager Community Repository

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Specific tag name"
        required: true
        type: string

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit package to Windows Package Manager Community Repository
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Lapce.Lapce
          version: ${{ inputs.tag_name || github.event.release.tag_name }}
          release-tag: ${{ inputs.tag_name || github.event.release.tag_name }}
          token: ${{ secrets.WINGET_ACC_TOKEN }}
          fork-user: lapce-winget
```
