### ISSUE TITLE
Show original key E instead of its symbol when used with Alt

### ISSUE THREAD

**Issue by eugenesvk** [lapce/lapce#2364]
## Is your feature request related to a problem? Please describe.

I've mapped <kbd>⎇</kbd><kbd>e</kbd> to show Command Palette, and my GUI settings and the config file show this instead of `e` (since this combo is inserting a symbol `€`):

```toml
[[keymaps]]
command = "palette.command"
key = "Alt+€"
```

## Describe the solution you'd like

Add an option for keymaps to only show the original keyboard letter `e`

## Describe alternatives you've considered

None

## Additional context

None
