### ISSUE TITLE
Abnormal Screen behavior

### ISSUE THREAD

**Issue by Marin-Kitagawa** [lapce/lapce#2385]
## Lapce Version

$0.2.7$

## System information

```yaml
Edition:	Windows 11 Pro
Version:	22H2
OS build:	22621.1702
Experience:	Windows Feature Experience Pack 1000.22641.1000.0
```

## Describe the bug
Consider the following actions
1. `Alt+Tab`
2. Clicking on any UI element inside Lapce

For the first one, switching to another application from Lapce or switching to Lapce from another application causes the screen to blink.

For the second one, clicking any UI element, for example, settings icon causes the screen to blink i.e. goes black for a second. When I open the settings (after clicking on settings icon), the screen goes black for longer time ($\approx 3$ s).
