### ISSUE TITLE
Add run configurations

### ISSUE THREAD

**Issue by john01dav** [lapce/lapce#2725]
## Is your feature request related to a problem? Please describe.

I am a long-time user of Jetbrains IDEs and I am trying Lapce because it performs better and is FOSS. But, I find myself missing Jetbrains-style run configurations.

## Describe the solution you'd like

I would like to see two files, a run_configurations.[toml|yml|json|whatever] and another local_run_configurations file (with the same format). Two files can be present to allow committing some configurations for other developers, and having a .gitignored set for local-only use.

Each run configuration should specify one or more commands to run, other configurations that run first, and have its output parsed usefully (meaning if it is, for example, a cargo command that outputs an error with a line number I want to be able to click on it  and jump to that code). Additionally, a key combination should be present to run the last run configuration and a drop down box to select others to run.

## Describe alternatives you've considered

Right now I just use the integrated terminal to run things, but this is a bit more tedious than having a simple key combination and a bit less organized than having specific run configurations.

**Comment by john01dav** [comment]
An example of what the configurations could look like is this (I used YAML since that's my personal favorite but it does not matter)
```yaml
run:
  commands:
    - cargo run
  run_first:
    - check
  options:
    - multiple_run # do not stop the last invocation when starting a new invocation
check:
  commands:
   - cargo check
```
