### ISSUE TITLE
Using LLDB in Rust, Immediately crash or exit Lapce with or without breakpoint

### ISSUE THREAD

**Issue by codeitlikemiley** [lapce/lapce#2871]
Hi , 
Ive been testing out lapce lldb with rust on MacOS M1

this is my current run.toml
```toml
# The run config is used for both run mode and debug mode

[[configs]]
# the name of this task
name = "codeitlikemiley"

# the type of the debugger. If not set, it can't be debugged but can still be run
type = "lldb"

# the program to run
program = "target/debug/lapce"


[configs.prelaunch]
program = "cargo"
args = [
  "build",
]
```

Ive installed llvm on brew as well

```
brew install llvm
```

Ive also added the llvm path to my .zshrc

```
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
```

From within Lapce settings Ive added  path of lldb-vscode

```
/opt/homebrew/opt/llvm/bin/lldb-vscode
```

Now, If i try to debug , with breakpoint , it just exit immediate lapce,

https://github.com/lapce/lapce-lldb/assets/28816690/fe25f61e-3b6a-4908-9f76-8f773c424045

While if I try to debug without breakpoint it would show the text hello-world print and exit Lapce.

I dont know if anyone here using MacOs is experiencing it, I already tried to report this on the maintainer of lapce-lldb

https://github.com/lapce/lapce-lldb/issues/1

I tried to posted it here as well. Hope any luck , that someone can also share their experience using lldb on rust with lapce
