### ISSUE TITLE
Single numbers don't work as keybinds

### ISSUE THREAD

**Issue by eugenesvk** [lapce/lapce#2887]
## Lapce Version

nightly-8312021

## System information

Windows 10

## Describe the bug

This keybinding doesn't work
```toml
[[keymaps]]
key = "1"
command = "previous_editor_tab"
mode = "nv"
```

This works
```toml
[[keymaps]]
key = "q"
command = "previous_editor_tab"
mode = "nv"
```

## Additional information

I guess this is due to special nature of numeric keybinds that work to repeat commands?
I'd prefer to use regular numbers for regular keybinds an for repetition to either :
  - use numpad numbers
  - require all repetition prefixes to have an extra mandatory `0` before
