### ISSUE TITLE
Sequenced keybindings don't work when a file tab is active

### ISSUE THREAD

**Issue by eugenesvk** [lapce/lapce#2888]
## Lapce Version

nightly-8312021

## System information

Windows 10

## Describe the bug

Sequences of keybinds don't work when a file tab is active (but do work when a settings/keybindings tab is opened)
```toml
[[keymaps]]
key = "Ctrl+. Ctrl+L"
command = "palette.palette_help"
```

This works (single keybind, no seqence)
```toml
[[keymaps]]
key = "Ctrl+L"
command = "palette.palette_help"
```

## Additional information

n/a
