### ISSUE TITLE
Multicursor doesn't work in normal mode

### ISSUE THREAD

**Issue by eugenesvk** [lapce/lapce#2889]
## Lapce Version

nightly-8312021

## System information

Windows 10

## Describe the bug

This keybinding to have multiple cursors doesn't work in normal mode, but works in insert mode
```toml
[[keymaps]]
key = "Alt+Up"
command = "insert_cursor_above"
mode = "nvi"
```

## Additional information

n/a
