### ISSUE TITLE
User friendly Keyboard Shortcuts config format

### ISSUE THREAD

**Issue by eugenesvk** [lapce/lapce#2891]
## Is your feature request related to a problem? Please describe.

Current configuration format is very verbose since it requires 3+ lines to define a single shortcut, so if you rebind a lot of them, the file becomes undreadable since you can't organize it in a similarly tabular fashion like the GUI (the GUI suffers from other limitations like lack of groups, comments, search by key name etc.)

For example, this is close to a third of a page for just two keys!
```toml
[[keymaps]]
key = "Escape"
command = "normal_mode"
mode = "inv"
when = "!search_focus && !modal_focus && !search_active && !inline_completion_visible"
[[keymaps]]
key = "Ctrl+I"
command = "normal_mode"
mode = "i"
when = "!search_focus && !modal_focus && !search_active && !inline_completion_visible"
```

Part of the issue is the TOML's simplistic nature: if you didn't need to support extra key-value pairs like "when" etc. you could make it work in a 1 shortcut per line.

## Describe the solution you'd like

A better config format with a much friendlier user experience without all the extra lines and even the extra noise of `"` quotes everywhere like this:

<img width="582" alt="ShortcutsConfig" src="https://github.com/lapce/lapce/assets/12956286/5f2e6fe6-5040-4d92-881b-bc1f00bc9628">

Or supporting multiple shortcuts for the same command in the same line like this:

<img width="353" alt="ShortcutsConfig2" src="https://github.com/lapce/lapce/assets/12956286/4b0868e3-8da1-4b26-9f35-53a786666e1a">

## Describe alternatives you've considered

The illustration above is from a modern KDL document language https://kdl.dev (has a Rust parser that roundtrips config preserving formatting, so will not degrade the current experience when using GUI to change shortcuts). It's one of the better user friendly config formats out there, but any other format that would allow simple tables with as little formatting overhead as possible would also work (though a lot of even the modern ones have weirdly restrictive rules on names).

## Additional context
The main two things missing here

1. Variables (so you could, e.g., define `$LeftOfSpace` key as `Alt` on Windows and `Cmd` on a Mac and use that variable in your config to have the same file work on different OSes), but I think even that can be simulated if you add some predefined group
```
user_variables {
  (mac)LeftOfSpace="Cmd" 
  (win)LeftOfSpace="Ctrl" 
}
```
(or maybe you could have a slightly more complicated example that could benefit from vars, like adding a single extra modifier in insert mode to the whole group of keybinds from your normal mode)

2. Imports so that you could split a huge config file into, e.g., Normal mode commands, and Insert mode commands. But think that can also be fixed by just loading all config formats with a `keymaps` prefix or having yet another predefined group in the main `keymaps` file
```
imports "keymaps_insert" "keymaps_normal"
```

**Comment by panekj** [comment]
That would require for us to bundle another de/serializer just for keymap config but also makes it completely unreadable and unfriendly (just because you can use KDL doesn't mean it's better for other people).

> It's one of the better user friendly config formats out there, 

I beg to differ

> 1. Variables

That can be done in Lapce itself since we already do it for themes.

> 2. Imports

I don't think we want to support such scenario, as keymaps are not a configuration type that would benefit from being split.

> Part of the issue is the TOML's simplistic nature: if you didn't need to support extra key-value pairs like "when" etc. you could make it work in a 1 shortcut per line.

The beauty of TOML is that it's exactly that, simple. It's easy to grasp the concept and edit as a human, but it mostly serves as a configuration backend, main interface is GUI.

**Comment by eugenesvk** [comment]
> > It's one of the better user friendly config formats out there,
> 
> I beg to differ

Based on what? I've mentioned a bunch of benefits, what's your argument? Why is the GUI organized as a vertically aligned table instead of the many-lined mess per key?

> The beauty of TOML is that it's exactly that, simple. It's easy to grasp the concept and edit as a human,

What's simple with having an unalined mess instead of a simple table? What's simple with having to repeat `[[keymaps]]`for every single key??? The toml-is-simple way could be an argument if you used 1 line per key like this
```toml
# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
a = "move_char_left" # Maps the 'a' key to the move_char_left command
w = "move_line_up" # Maps the 'w' key move_line_up
"C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
[keys.insert]
```


>   but it mostly serves as a configuration backend, main interface is GUI.

The "main" GUI interface has too many issues (also listed in the post), so it's not suitable for remapping a lot of keys, currently its only benefit is that it's easier to press keys to set them (but only for short sequences) than type them

> > 1. Variables
> 
> That can be done in Lapce itself since we already do it for themes.

How would you enter those variables in the shortcut field that currently only accepts keys? And you can also set shortcuts in "Lapce itself", that doesn't prevent you from having a config that has them that you can edit easier in an editor with all the text editing benefits that GUIs don't offer (simple things like batch replace). Plus you can have better backups and version control.

> 
> > 2. Imports
> 
> I don't think we want to support such scenario, as keymaps are not a configuration type that would benefit from being split.

Keymaps are exactly that configuration type since they can have hundreds or even thousands of lines, so search&edit becomes a chore without modules, and I've mentioned an example of logic you could use to split those configs: modes. Another logic would be extensions where you'd have a separate file to configure extension-specific keymaps.
