### ISSUE TITLE
Add default layout config opion(s)

### ISSUE THREAD

**Issue by timon-schelling** [lapce/lapce#3197]
## Problem

I want to use lapce inside a fully declarative system config. Therefore I don't like that some options mainly concerning layout cannot be set via config and are only available at runtime in the UI.

## Proposed Solution

Add a `default_layout` (maybe `ui.layout` or `ui.default_layout`) section to the config that sets a default position and size for all panels. 

Something like:
```toml
[ui.layout]
bottom_panels_hidden = true
left_panels_hidden = true
right_panels_hidden = false

[ui.layout.file_explorer]
position = "right_top"
size = 200

[ui.layout.terminal]
position = "bottom_right"
size = 400
```
I'm not sure how panel ordering should be handled.

Something like the following seems weird
```toml
[ui.layout.file_explorer]
tab = 0

[ui.layout.terminal]
tab = 1
```
and
```toml
[ui.layout.bottom_panels]
hidden = false
order = ["terminal", "file_explorer"]
```
is even worse.

## Additional context

I want this for integration with home manager (nix os). Currently the only option I have
is to patch lapce before building it. Not that bad with nix, but recompiling my editor because I want to change the layout is annoying.
