### ISSUE TITLE
Visual bug in the built-in Lapce terminal

### ISSUE THREAD

**Issue by cauliflowew** [lapce/lapce#345]
I noticed that the built-in Lapce terminal always ignores the UNIX dollar sign in the prompt, and places the cursor right on top of it, as opposed to to the right of the dollar sign. Additionally, if you quit the execution of a program using `ctrl+c`, then the cursor will just go onto file path in the command line. Visual demonstration below (since it's a visual bug):

https://user-images.githubusercontent.com/82113833/161322620-62b4ffb6-74d3-4fc3-9097-9de60a98b5d1.mov

**Comment by felipetesc** [comment]
Hello there.  You are creating a great project. Congrats.

I'm having a problem with the built-in Lapce terminal as well.

Info:
OS : Garuda Linux x64 (based on arch)
Rust version: rustc 1.61.0 (fe5b13d68 2022-05-18)
Lapce Version:  "0.1.2"
Date of build: 06.24.22
Build result: ok
Used shell: bash and fish
Tested commands: clear, bash and fish

![error_render_terminal](https://user-images.githubusercontent.com/2336812/175467604-5b3b5d94-8172-48cd-a3e9-5bae06e6a4c9.gif)

**Comment by felipetesc** [comment]
> @felipetesc Can you try setting the line height in the terminal settings to something like 12 (it defaults to 0, which means the editor line height)?

Thank you for the quick reply. I changed to 20 (12 wasn't enough ) and it seems better now

**Comment by MinusGix** [comment]
> > @felipetesc Can you try setting the line height in the terminal settings to something like 12 (it defaults to 0, which means the editor line height)?
> 
> Thank you for the quick reply. I changed to 20 (12 wasn't enough ) and it seems better now

Hm, did you change the font family / font size for the terminal separately from the editor (since I assume it hasn't happened in the editor)? If so the bug might be that we need to do smarter line height calculations since the terminal font might simply be too big / whatever relative to the default case of using the editors line height, though it is weird.

**Comment by felipetesc** [comment]
> > > @felipetesc Can you try setting the line height in the terminal settings to something like 12 (it defaults to 0, which means the editor line height)?
> > 
> > 
> > Thank you for the quick reply. I changed to 20 (12 wasn't enough ) and it seems better now
> 
> Hm, did you change the font family / font size for the terminal separately from the editor (since I assume it hasn't happened in the editor)? If so the bug might be that we need to do smarter line height calculations since the terminal font might simply be too big / whatever relative to the default case of using the editors line height, though it is weird.

Yes, you are correct, I did change the font type. I also changed several other UI settings. I think it might be better to post the theme properties for further analysis.

Theme File

```toml
[theme]
name = "Sweet Raw Theme"

[theme.base]
white = "#ABB2BF"
black = "#282C34"
grey = "#3E4451"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56B6C2"
magenta = "#C678DD"

[theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#5C6370"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
selfKeyword = "$purple"
string = "$green"
struct = "$yellow"
structure = "$yellow"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
"variable.other.member" = "$red"

[theme.ui]
"activity.background" = "#181b28"
"activity.current" = "#181b28"
"completion.background" = "#181b28"
"completion.current" = "#2C313A"
"editor.background" = "#181b28"
"editor.caret" = "#528BFF"
"editor.current_line" = "#2C313C"
"editor.dim" = "#5C6370"
"editor.focus" = "#c50ed2"
"editor.foreground" = "$white"
"editor.link" = "$cyan"
"editor.selection" = "$grey"
"hover.background" = "#21252B"
"lapce.active_tab" = "#10121f"
"lapce.border" = "#10121f"
"lapce.dropdown_shadow" = "#10121f"
"lapce.error" = "$red"
"lapce.inactive_tab" = "$grey"
"lapce.scroll_bar" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#0c0e14"
"palette.current" = "#202d40"
"panel.background" = "#171926"
"panel.current" = "#2C313A"
"panel.hovered" = "#343A45"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#171926"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "#171926"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = "Roboto"
font-size = 14
header-height = 40
status-height = 30
tab-min-width = 120
activity-width = 50
scroll-width = 15
drop-shadow-width = 1

```
