### ISSUE TITLE
Lapce syntax highlighting issue 

### ISSUE THREAD

**Issue by MaskedTrench** [lapce/lapce#951]
## System: 
```yaml
OS: MacOS, 12.2
Chip: Apple M1
Cargo: 1.62.0 (a748cf5a3 2022-06-08)
Rustc: 1.62.1
```

## Problem:
Here is the [video](https://www.youtube.com/watch?v=XV9msrNxZaQ). The way it looks like:

1. Installing Rust extension
2. Openning directory
3. Finding out that highlight is not working -> Reloading Lapce
4. Opening directory once again
5. Reloading window
6. Pressing esc
7. Highlighting not working

I don't know actually why that happening and the theme is changing incorrectly, but id does
